/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mcy_geo3d_lib_NStringUtil */

#ifndef _Included_com_mcy_geo3d_lib_NStringUtil
#define _Included_com_mcy_geo3d_lib_NStringUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mcy_geo3d_lib_NStringUtil
 * Method:    getNativeString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mcy_geo3d_lib_NStringUtil_getNativeString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
